<?php
namespace App\Http\Controllers\Vadim\Myformreq;
use Illuminate\Foundation\Http\FormRequest;
class FormController extends FormRequest {
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'email' =>'email',
            'fname'=>'min:5|max:10'
            //
        ];
    }

    public function attributes()
    {
        return [
            'fname'=>'Имя',
            'email'=>'Почта'
        ];
        //return parent::attributes(); // TODO: Change the autogenerated stub
    }
    public function messages()
    {
        return [
            'email.email'=>'Неправильная почта3333'
        ];

    }
}