<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class ContactRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'email' =>'email',
            'fname'=>'min:5|max:10'
            //
        ];
    }
    public function attributes()
    {
        return [
            'fname'=>'Имя',
            'email'=>'Почта'
        ];
        //return parent::attributes(); // TODO: Change the autogenerated stub
    }
      public function messages()
      {
          return [
              'email.email'=>'Неправильная почта'
          ];

      }

}
